services:
  memgraph:
    image: memgraph/memgraph-mage:3.2
    container_name: memgraph-mage
    pull_policy: if_not_present
    ports:
      - "7687:7687"
      - "7444:7444"
    command: ["--log-level=TRACE"]

  lab:
    image: memgraph/lab:3.2.0
    container_name: memgraph-lab
    pull_policy: if_not_present
    ports:
      - "3000:3000"
    depends_on:
      - memgraph
    environment:
      - QUICK_CONNECT_MG_HOST=memgraph
      - QUICK_CONNECT_MG_PORT=7687
